Update Simplified Chinese Translation.
KRTirtho/spotube pull request #1162
Opened 2024-01-27 13:38 UTC by iceyear

Simplified Chinese Translation has been optimized and updated. Thanks a lot !

2024-02-17 20:58 UTC, varshith257 approved these changes
I think better to raise a issue and link a PR it resolves or fixes
Otherwise LGTM

2024-02-17 21:01 UTC, varshith257 requested changes
Fix lint checks

2024-05-10 17:02 UTC, KRTirtho commented
Please resolve the conflicts 🙏

2024-05-11 12:00 UTC, iceyear commented
> Please resolve the conflicts 🙏

I'm a bit busy right now🥺, but I'll fix it when I have time in the future. For now, let's close this PR.

2024-05-11 12:00 UTC, closed without merging