Added method to fetch lyrics  from AZLyrics as a fallback
KRTirtho/spotube pull request #1251
Opened 2024-02-21 20:32 UTC by Spectre-hidN

Spotify's official lyrics for many songs are not available for non-premium users. So, both synced and unsynced lyrics tabs will throw an error. But, now, it will fetch the unsynced lyrics of the currently playing track from Azlyrics as a fallback.
It uses the raw lyrics from the website, with no formatting or cleanups. So, for that reason, some non-UTF characters will break when it is rendered on the lyrics tab.

2024-02-24 14:49 UTC, KRTirtho requested changes

2024-02-24 14:49 UTC, KRTirtho commented on lib/utils/service_utils.dart
> +      HttpHeaders.hostHeader: "www.azlyrics.com",
`HttpHeaders` are exported from `dart:io` but it wasn't imported here

2024-02-24 14:53 UTC, KRTirtho commented
Also, results are not that great. Hardly shows up for tracks except US/UK/ES one's
I think genius.com has a wider collection of lyrics, so implementing it instead of AZLyrics should provide much better results

2024-02-24 17:10 UTC, Spectre-hidN commented
Also, results are not that great. Hardly shows up for tracks except US/UK/ES one's
I think genius.com has a wider collection of lyrics, so implementing it instead of AZLyrics should provide much better results

Genius requires an access token to use its official API. Also, it might hit Error 429 if a user requests too many times. So, scraping the lyrics from a website is a better way to fetch the lyrics. I'll try my luck scraping the website if that doesn't violate their TOS.

2024-07-29 15:48 UTC, lightdarkmaster approved these changes

2025-09-08 14:07 UTC, KRTirtho commented
Thanks for the contribution. 

Since the implementation of LRCLIB using Genius or AZLyrics has become unnecessary. So I'm closing it

2025-09-08 14:07 UTC, closed without merging