translate to catalan
KRTirtho/spotube pull request #621
Opened 2023-08-09 09:08 UTC by sf0nt

2023-08-09 15:41 UTC, KRTirtho requested changes

2023-08-09 20:58 UTC, sf0nt commented on lib/l10n/l10n.dart
> +    const Locale('ca', 'CA'),
Andorra it's OK. I am going to change it

2023-08-09 21:02 UTC, sf0nt commented on lib/l10n/l10n.dart
> +    const Locale('ca', 'CA'),
done

2023-08-15 05:58 UTC, KRTirtho commented
Thanks for this wonderful contribution & Catalan is lovely language :heart:

2023-08-15 06:01 UTC, KRTirtho approved these changes

2023-08-15 06:02 UTC, merged