feat: Enhance mobile responsiveness
KRTirtho/spotube pull request #647
Opened 2023-08-22 04:47 UTC by ElonMusk2002

Adjusted the code to improve the display and functionality on mobile devices. This includes responsive design updates and layout adjustments to ensure a better user experience on smaller screens.

**Changes Made:**

- Improved mobile responsiveness for a better user experience.
- Implemented responsive design updates and layout adjustments.

**Before:**
- Before the changes, the main page on mobile devices appeared somewhat distorted, as shown in the "before" screenshots.

![before2](https://github.com/KRTirtho/spotube/assets/113548499/dc093d0c-f601-4cd6-a339-e35ba61d7fc7)
![before1](https://github.com/KRTirtho/spotube/assets/113548499/d29d40b5-71a9-469b-ad0b-fad1c7d929e6)

**After:**
- After making these adjustments, the page now offers a more polished and user-friendly experience on mobile devices, as depicted in the "after" screenshots.

![after2](https://github.com/KRTirtho/spotube/assets/113548499/984f2e38-0042-4ac5-a4e0-908177e74283)
![after1](https://github.com/KRTirtho/spotube/assets/113548499/9c3d3cd0-f6fd-433d-b787-8bed7cf13a93)

2023-08-22 08:33 UTC, KRTirtho commented
Awesome work :rocket: 
But can you revert the package-lock.json changes as it's unrelated to this issue? :smile:

2023-08-22 11:18 UTC, KRTirtho requested changes

2023-08-22 14:06 UTC, ElonMusk2002 commented on website/package-lock.json
done

2023-08-22 14:08 UTC, ElonMusk2002 commented
My apologies for that! Now, if everything looks good, please go ahead and submit a pull request. 🚀

2023-08-23 04:08 UTC, KRTirtho approved these changes

2023-08-23 04:08 UTC, merged