Improve logging framework
KRTirtho/spotube pull request #712
Opened 2023-09-10 23:22 UTC by meenbeese

This PR enhances our discombobulated logging framework by unifying all logs through our custom logger utility, replacing the use of `print` and `debugPrint` methods as suggested by Flutter. I have updated the `logger` library to the latest version and removed the unused `logging` library from our dependencies. These changes streamline debugging across various packages, methods, and classes for improved efficiency.

2023-09-11 01:12 UTC, meenbeese commented
I had some issues with conflicting commits and rebases but they should be fixed now.

2023-09-12 09:32 UTC, KRTirtho requested changes

2023-09-12 09:32 UTC, KRTirtho commented on lib/main.dart
> +  final logger = getLogger("Spotube");
Why do we need it here?

2023-09-12 09:32 UTC, KRTirtho commented on bin/gen-credits.dart
> +  final logger = getLogger("GenCredits");
Please revert this file's changes. It's not for debug purposes. The output needs not to be decorated

2023-09-12 09:32 UTC, KRTirtho commented on bin/untranslated_messages.dart
> +  final logger = getLogger("UntranslatedMessages");
Revert this one as well. We need clean logs not decorated logs

2023-09-12 09:32 UTC, KRTirtho commented on bin/verify-pkgbuild.dart
> +      logger.d("[Failed to parse PKGBUILD] $e");
This should be `logger.e`

2023-09-12 09:32 UTC, KRTirtho commented on lib/provider/proxy_playlist/next_fetcher_mixin.dart
> +      logger.d(e.toString());
`logger.e` should be used

2023-09-20 00:46 UTC, meenbeese commented
Messed up this PR very badly, opening a new one...

2023-09-20 00:46 UTC, closed without merging